version: "3.8"

services:
  todo-todo:
    build: ./Todos
    command: "node index.js"
    image: adhxabre/todo-todos
    restart: always
    container_name: todo_todos
    ports:
      - 5002:5002

  todo-users:
    build: ./Users
    command: "go run ."
    image: adhxabre/todo-users
    restart: always
    container_name: todo_users
    ports:
      - 5000:5000
