version: '3.8'
services:
    database:
        image: mysql:latest
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - ~/mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD='123'
            - MYSQL_USERNAME='root'
            - MYSQL_PASSWORD='123'
            - MYSQL_DATABASE='waystodo'
    backend:
        restart: always
        build: .
        container_name: user-services
        ports:
            - '5000:5000'